version: "3.5"
services: 
  app:
    image: node:12
    volumes:
      - .:/app
    working_dir: /app
    command: ['npm', 'run', 'dev']
  redis:
    image: redis:latest
  mysql:
    image: mariadb:10.4
    volumes:
      - vmysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_ROOT_HOST: "%"
volumes:
  vmysql:
